version: '3.9'

services:
  backend:
    image: node:18
    container_name: backend
    working_dir: /usr/src/app
    volumes:
      - ./services/backend:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=mydatabase
    depends_on:
      - db
    command: sh -c "npm install && npm run dev"

  frontend:
    image: node:18
    container_name: frontend
    working_dir: /usr/src/app
    volumes:
      - ./services/frontend:/usr/src/app
    ports:
      - "3001:3000"
    command: sh -c "npm install && npm run dev"

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
    ports:
      - "3334:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8085:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db_data:
