
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AccountProfile': typeof import("../components/account/AccountProfile.vue")['default']
    'AppBar': typeof import("../components/app/AppBar.vue")['default']
    'AppBarNotification': typeof import("../components/app/AppBarNotification.vue")['default']
    'AppBarProfile': typeof import("../components/app/AppBarProfile.vue")['default']
    'AppBarSearch': typeof import("../components/app/AppBarSearch.vue")['default']
    'AppSideBar': typeof import("../components/app/AppSideBar.vue")['default']
    'CommonLabel': typeof import("../components/common/CommonLabel.vue")['default']
    'QuoteLineChart': typeof import("../components/quote/LineChart.vue")['default']
    'QuotePieChart': typeof import("../components/quote/PieChart.vue")['default']
    'QuoteRecent': typeof import("../components/quote/QuoteRecent.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NaiveConfig': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveConfig.vue")['default']
    'NaiveNavbar': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNavbar.vue")['default']
    'NaiveColorModeSwitch': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveColorModeSwitch.vue")['default']
    'NaiveTabbar': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveTabbar.vue")['default']
    'NaiveMenuLink': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveMenuLink.vue")['default']
    'NaiveLayoutSidebar': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutSidebar.vue")['default']
    'NaiveLayoutNavbar': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutNavbar.vue")['default']
    'NaiveDrawerLink': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveDrawerLink.client.vue")['default']
    'NaiveLoadingBar': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLoadingBar.client.vue")['default']
    'NaiveNotification': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNotification.client.vue")['default']
    'NaiveIcon': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveIcon.vue")['default']
    'NThemeEditor': typeof import("naive-ui")['NThemeEditor']
    'NAffix': typeof import("naive-ui")['NAffix']
    'NAlert': typeof import("naive-ui")['NAlert']
    'NAnchor': typeof import("naive-ui")['NAnchor']
    'NAnchorLink': typeof import("naive-ui")['NAnchorLink']
    'NAutoComplete': typeof import("naive-ui")['NAutoComplete']
    'NAvatar': typeof import("naive-ui")['NAvatar']
    'NAvatarGroup': typeof import("naive-ui")['NAvatarGroup']
    'NBackTop': typeof import("naive-ui")['NBackTop']
    'NBadge': typeof import("naive-ui")['NBadge']
    'NBreadcrumb': typeof import("naive-ui")['NBreadcrumb']
    'NBreadcrumbItem': typeof import("naive-ui")['NBreadcrumbItem']
    'NButton': typeof import("naive-ui")['NButton']
    'NButtonGroup': typeof import("naive-ui")['NButtonGroup']
    'NCalendar': typeof import("naive-ui")['NCalendar']
    'NCard': typeof import("naive-ui")['NCard']
    'NCarousel': typeof import("naive-ui")['NCarousel']
    'NCarouselItem': typeof import("naive-ui")['NCarouselItem']
    'NCascader': typeof import("naive-ui")['NCascader']
    'NCheckbox': typeof import("naive-ui")['NCheckbox']
    'NCheckboxGroup': typeof import("naive-ui")['NCheckboxGroup']
    'NCode': typeof import("naive-ui")['NCode']
    'NCollapse': typeof import("naive-ui")['NCollapse']
    'NCollapseItem': typeof import("naive-ui")['NCollapseItem']
    'NCollapseTransition': typeof import("naive-ui")['NCollapseTransition']
    'NColorPicker': typeof import("naive-ui")['NColorPicker']
    'NConfigProvider': typeof import("naive-ui")['NConfigProvider']
    'NCountdown': typeof import("naive-ui")['NCountdown']
    'NDataTable': typeof import("naive-ui")['NDataTable']
    'NDatePicker': typeof import("naive-ui")['NDatePicker']
    'NDescriptions': typeof import("naive-ui")['NDescriptions']
    'NDescriptionsItem': typeof import("naive-ui")['NDescriptionsItem']
    'NDialog': typeof import("naive-ui")['NDialog']
    'NDialogProvider': typeof import("naive-ui")['NDialogProvider']
    'NDivider': typeof import("naive-ui")['NDivider']
    'NDrawer': typeof import("naive-ui")['NDrawer']
    'NDrawerContent': typeof import("naive-ui")['NDrawerContent']
    'NDropdown': typeof import("naive-ui")['NDropdown']
    'NDynamicInput': typeof import("naive-ui")['NDynamicInput']
    'NDynamicTags': typeof import("naive-ui")['NDynamicTags']
    'NElement': typeof import("naive-ui")['NElement']
    'NEl': typeof import("naive-ui")['NEl']
    'NEllipsis': typeof import("naive-ui")['NEllipsis']
    'NPerformantEllipsis': typeof import("naive-ui")['NPerformantEllipsis']
    'NEmpty': typeof import("naive-ui")['NEmpty']
    'NEquation': typeof import("naive-ui")['NEquation']
    'NFlex': typeof import("naive-ui")['NFlex']
    'NFloatButton': typeof import("naive-ui")['NFloatButton']
    'NFloatButtonGroup': typeof import("naive-ui")['NFloatButtonGroup']
    'NForm': typeof import("naive-ui")['NForm']
    'NFormItem': typeof import("naive-ui")['NFormItem']
    'NFormItemCol': typeof import("naive-ui")['NFormItemCol']
    'NFormItemGridItem': typeof import("naive-ui")['NFormItemGridItem']
    'NFormItemGi': typeof import("naive-ui")['NFormItemGi']
    'NFormItemRow': typeof import("naive-ui")['NFormItemRow']
    'NGlobalStyle': typeof import("naive-ui")['NGlobalStyle']
    'NGradientText': typeof import("naive-ui")['NGradientText']
    'NGrid': typeof import("naive-ui")['NGrid']
    'NGridItem': typeof import("naive-ui")['NGridItem']
    'NGi': typeof import("naive-ui")['NGi']
    'NHighlight': typeof import("naive-ui")['NHighlight']
    'NIcon': typeof import("naive-ui")['NIcon']
    'NIconWrapper': typeof import("naive-ui")['NIconWrapper']
    'NImage': typeof import("naive-ui")['NImage']
    'NImageGroup': typeof import("naive-ui")['NImageGroup']
    'NInfiniteScroll': typeof import("naive-ui")['NInfiniteScroll']
    'NInput': typeof import("naive-ui")['NInput']
    'NInputGroup': typeof import("naive-ui")['NInputGroup']
    'NInputGroupLabel': typeof import("naive-ui")['NInputGroupLabel']
    'NInputNumber': typeof import("naive-ui")['NInputNumber']
    'NLayout': typeof import("naive-ui")['NLayout']
    'NLayoutContent': typeof import("naive-ui")['NLayoutContent']
    'NLayoutFooter': typeof import("naive-ui")['NLayoutFooter']
    'NLayoutHeader': typeof import("naive-ui")['NLayoutHeader']
    'NLayoutSider': typeof import("naive-ui")['NLayoutSider']
    'NCol': typeof import("naive-ui")['NCol']
    'NRow': typeof import("naive-ui")['NRow']
    'NLegacyTransfer': typeof import("naive-ui")['NLegacyTransfer']
    'NList': typeof import("naive-ui")['NList']
    'NListItem': typeof import("naive-ui")['NListItem']
    'NLoadingBarProvider': typeof import("naive-ui")['NLoadingBarProvider']
    'NLog': typeof import("naive-ui")['NLog']
    'NMarqueue': typeof import("naive-ui")['NMarqueue']
    'NMention': typeof import("naive-ui")['NMention']
    'NMenu': typeof import("naive-ui")['NMenu']
    'NMessageProvider': typeof import("naive-ui")['NMessageProvider']
    'NModal': typeof import("naive-ui")['NModal']
    'NModalProvider': typeof import("naive-ui")['NModalProvider']
    'NNotificationProvider': typeof import("naive-ui")['NNotificationProvider']
    'NNumberAnimation': typeof import("naive-ui")['NNumberAnimation']
    'NPageHeader': typeof import("naive-ui")['NPageHeader']
    'NPagination': typeof import("naive-ui")['NPagination']
    'NPopconfirm': typeof import("naive-ui")['NPopconfirm']
    'NPopover': typeof import("naive-ui")['NPopover']
    'NPopselect': typeof import("naive-ui")['NPopselect']
    'NProgress': typeof import("naive-ui")['NProgress']
    'NQrCode': typeof import("naive-ui")['NQrCode']
    'NRadio': typeof import("naive-ui")['NRadio']
    'NRadioButton': typeof import("naive-ui")['NRadioButton']
    'NRadioGroup': typeof import("naive-ui")['NRadioGroup']
    'NRate': typeof import("naive-ui")['NRate']
    'NResult': typeof import("naive-ui")['NResult']
    'NScrollbar': typeof import("naive-ui")['NScrollbar']
    'NSelect': typeof import("naive-ui")['NSelect']
    'NSkeleton': typeof import("naive-ui")['NSkeleton']
    'NSlider': typeof import("naive-ui")['NSlider']
    'NSpace': typeof import("naive-ui")['NSpace']
    'NSpin': typeof import("naive-ui")['NSpin']
    'NSplit': typeof import("naive-ui")['NSplit']
    'NStatistic': typeof import("naive-ui")['NStatistic']
    'NStep': typeof import("naive-ui")['NStep']
    'NSteps': typeof import("naive-ui")['NSteps']
    'NSwitch': typeof import("naive-ui")['NSwitch']
    'NTable': typeof import("naive-ui")['NTable']
    'NTbody': typeof import("naive-ui")['NTbody']
    'NTd': typeof import("naive-ui")['NTd']
    'NTh': typeof import("naive-ui")['NTh']
    'NThead': typeof import("naive-ui")['NThead']
    'NTr': typeof import("naive-ui")['NTr']
    'NTab': typeof import("naive-ui")['NTab']
    'NTabPane': typeof import("naive-ui")['NTabPane']
    'NTabs': typeof import("naive-ui")['NTabs']
    'NTag': typeof import("naive-ui")['NTag']
    'NThing': typeof import("naive-ui")['NThing']
    'NTime': typeof import("naive-ui")['NTime']
    'NTimePicker': typeof import("naive-ui")['NTimePicker']
    'NTimeline': typeof import("naive-ui")['NTimeline']
    'NTimelineItem': typeof import("naive-ui")['NTimelineItem']
    'NTooltip': typeof import("naive-ui")['NTooltip']
    'NTransfer': typeof import("naive-ui")['NTransfer']
    'NTree': typeof import("naive-ui")['NTree']
    'NTreeSelect': typeof import("naive-ui")['NTreeSelect']
    'NA': typeof import("naive-ui")['NA']
    'NBlockquote': typeof import("naive-ui")['NBlockquote']
    'NH1': typeof import("naive-ui")['NH1']
    'NH2': typeof import("naive-ui")['NH2']
    'NH3': typeof import("naive-ui")['NH3']
    'NH4': typeof import("naive-ui")['NH4']
    'NH5': typeof import("naive-ui")['NH5']
    'NH6': typeof import("naive-ui")['NH6']
    'NHr': typeof import("naive-ui")['NHr']
    'NLi': typeof import("naive-ui")['NLi']
    'NOl': typeof import("naive-ui")['NOl']
    'NP': typeof import("naive-ui")['NP']
    'NText': typeof import("naive-ui")['NText']
    'NUl': typeof import("naive-ui")['NUl']
    'NUpload': typeof import("naive-ui")['NUpload']
    'NUploadDragger': typeof import("naive-ui")['NUploadDragger']
    'NUploadFileList': typeof import("naive-ui")['NUploadFileList']
    'NUploadTrigger': typeof import("naive-ui")['NUploadTrigger']
    'NVirtualList': typeof import("naive-ui")['NVirtualList']
    'NWatermark': typeof import("naive-ui")['NWatermark']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'NaiveDrawerLink': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'NaiveLoadingBar': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'NaiveNotification': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'NDrawer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['NDrawer']>
    'NDrawerContent': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['NDrawerContent']>
    'NModal': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['NModal']>
      'LazyAccountProfile': typeof import("../components/account/AccountProfile.vue")['default']
    'LazyAppBar': typeof import("../components/app/AppBar.vue")['default']
    'LazyAppBarNotification': typeof import("../components/app/AppBarNotification.vue")['default']
    'LazyAppBarProfile': typeof import("../components/app/AppBarProfile.vue")['default']
    'LazyAppBarSearch': typeof import("../components/app/AppBarSearch.vue")['default']
    'LazyAppSideBar': typeof import("../components/app/AppSideBar.vue")['default']
    'LazyCommonLabel': typeof import("../components/common/CommonLabel.vue")['default']
    'LazyQuoteLineChart': typeof import("../components/quote/LineChart.vue")['default']
    'LazyQuotePieChart': typeof import("../components/quote/PieChart.vue")['default']
    'LazyQuoteRecent': typeof import("../components/quote/QuoteRecent.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNaiveConfig': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveConfig.vue")['default']
    'LazyNaiveNavbar': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNavbar.vue")['default']
    'LazyNaiveColorModeSwitch': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveColorModeSwitch.vue")['default']
    'LazyNaiveTabbar': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveTabbar.vue")['default']
    'LazyNaiveMenuLink': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveMenuLink.vue")['default']
    'LazyNaiveLayoutSidebar': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutSidebar.vue")['default']
    'LazyNaiveLayoutNavbar': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutNavbar.vue")['default']
    'LazyNaiveDrawerLink': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveDrawerLink.client.vue")['default']
    'LazyNaiveLoadingBar': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLoadingBar.client.vue")['default']
    'LazyNaiveNotification': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNotification.client.vue")['default']
    'LazyNaiveIcon': typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveIcon.vue")['default']
    'LazyNThemeEditor': typeof import("naive-ui")['NThemeEditor']
    'LazyNAffix': typeof import("naive-ui")['NAffix']
    'LazyNAlert': typeof import("naive-ui")['NAlert']
    'LazyNAnchor': typeof import("naive-ui")['NAnchor']
    'LazyNAnchorLink': typeof import("naive-ui")['NAnchorLink']
    'LazyNAutoComplete': typeof import("naive-ui")['NAutoComplete']
    'LazyNAvatar': typeof import("naive-ui")['NAvatar']
    'LazyNAvatarGroup': typeof import("naive-ui")['NAvatarGroup']
    'LazyNBackTop': typeof import("naive-ui")['NBackTop']
    'LazyNBadge': typeof import("naive-ui")['NBadge']
    'LazyNBreadcrumb': typeof import("naive-ui")['NBreadcrumb']
    'LazyNBreadcrumbItem': typeof import("naive-ui")['NBreadcrumbItem']
    'LazyNButton': typeof import("naive-ui")['NButton']
    'LazyNButtonGroup': typeof import("naive-ui")['NButtonGroup']
    'LazyNCalendar': typeof import("naive-ui")['NCalendar']
    'LazyNCard': typeof import("naive-ui")['NCard']
    'LazyNCarousel': typeof import("naive-ui")['NCarousel']
    'LazyNCarouselItem': typeof import("naive-ui")['NCarouselItem']
    'LazyNCascader': typeof import("naive-ui")['NCascader']
    'LazyNCheckbox': typeof import("naive-ui")['NCheckbox']
    'LazyNCheckboxGroup': typeof import("naive-ui")['NCheckboxGroup']
    'LazyNCode': typeof import("naive-ui")['NCode']
    'LazyNCollapse': typeof import("naive-ui")['NCollapse']
    'LazyNCollapseItem': typeof import("naive-ui")['NCollapseItem']
    'LazyNCollapseTransition': typeof import("naive-ui")['NCollapseTransition']
    'LazyNColorPicker': typeof import("naive-ui")['NColorPicker']
    'LazyNConfigProvider': typeof import("naive-ui")['NConfigProvider']
    'LazyNCountdown': typeof import("naive-ui")['NCountdown']
    'LazyNDataTable': typeof import("naive-ui")['NDataTable']
    'LazyNDatePicker': typeof import("naive-ui")['NDatePicker']
    'LazyNDescriptions': typeof import("naive-ui")['NDescriptions']
    'LazyNDescriptionsItem': typeof import("naive-ui")['NDescriptionsItem']
    'LazyNDialog': typeof import("naive-ui")['NDialog']
    'LazyNDialogProvider': typeof import("naive-ui")['NDialogProvider']
    'LazyNDivider': typeof import("naive-ui")['NDivider']
    'LazyNDrawer': typeof import("naive-ui")['NDrawer']
    'LazyNDrawerContent': typeof import("naive-ui")['NDrawerContent']
    'LazyNDropdown': typeof import("naive-ui")['NDropdown']
    'LazyNDynamicInput': typeof import("naive-ui")['NDynamicInput']
    'LazyNDynamicTags': typeof import("naive-ui")['NDynamicTags']
    'LazyNElement': typeof import("naive-ui")['NElement']
    'LazyNEl': typeof import("naive-ui")['NEl']
    'LazyNEllipsis': typeof import("naive-ui")['NEllipsis']
    'LazyNPerformantEllipsis': typeof import("naive-ui")['NPerformantEllipsis']
    'LazyNEmpty': typeof import("naive-ui")['NEmpty']
    'LazyNEquation': typeof import("naive-ui")['NEquation']
    'LazyNFlex': typeof import("naive-ui")['NFlex']
    'LazyNFloatButton': typeof import("naive-ui")['NFloatButton']
    'LazyNFloatButtonGroup': typeof import("naive-ui")['NFloatButtonGroup']
    'LazyNForm': typeof import("naive-ui")['NForm']
    'LazyNFormItem': typeof import("naive-ui")['NFormItem']
    'LazyNFormItemCol': typeof import("naive-ui")['NFormItemCol']
    'LazyNFormItemGridItem': typeof import("naive-ui")['NFormItemGridItem']
    'LazyNFormItemGi': typeof import("naive-ui")['NFormItemGi']
    'LazyNFormItemRow': typeof import("naive-ui")['NFormItemRow']
    'LazyNGlobalStyle': typeof import("naive-ui")['NGlobalStyle']
    'LazyNGradientText': typeof import("naive-ui")['NGradientText']
    'LazyNGrid': typeof import("naive-ui")['NGrid']
    'LazyNGridItem': typeof import("naive-ui")['NGridItem']
    'LazyNGi': typeof import("naive-ui")['NGi']
    'LazyNHighlight': typeof import("naive-ui")['NHighlight']
    'LazyNIcon': typeof import("naive-ui")['NIcon']
    'LazyNIconWrapper': typeof import("naive-ui")['NIconWrapper']
    'LazyNImage': typeof import("naive-ui")['NImage']
    'LazyNImageGroup': typeof import("naive-ui")['NImageGroup']
    'LazyNInfiniteScroll': typeof import("naive-ui")['NInfiniteScroll']
    'LazyNInput': typeof import("naive-ui")['NInput']
    'LazyNInputGroup': typeof import("naive-ui")['NInputGroup']
    'LazyNInputGroupLabel': typeof import("naive-ui")['NInputGroupLabel']
    'LazyNInputNumber': typeof import("naive-ui")['NInputNumber']
    'LazyNLayout': typeof import("naive-ui")['NLayout']
    'LazyNLayoutContent': typeof import("naive-ui")['NLayoutContent']
    'LazyNLayoutFooter': typeof import("naive-ui")['NLayoutFooter']
    'LazyNLayoutHeader': typeof import("naive-ui")['NLayoutHeader']
    'LazyNLayoutSider': typeof import("naive-ui")['NLayoutSider']
    'LazyNCol': typeof import("naive-ui")['NCol']
    'LazyNRow': typeof import("naive-ui")['NRow']
    'LazyNLegacyTransfer': typeof import("naive-ui")['NLegacyTransfer']
    'LazyNList': typeof import("naive-ui")['NList']
    'LazyNListItem': typeof import("naive-ui")['NListItem']
    'LazyNLoadingBarProvider': typeof import("naive-ui")['NLoadingBarProvider']
    'LazyNLog': typeof import("naive-ui")['NLog']
    'LazyNMarqueue': typeof import("naive-ui")['NMarqueue']
    'LazyNMention': typeof import("naive-ui")['NMention']
    'LazyNMenu': typeof import("naive-ui")['NMenu']
    'LazyNMessageProvider': typeof import("naive-ui")['NMessageProvider']
    'LazyNModal': typeof import("naive-ui")['NModal']
    'LazyNModalProvider': typeof import("naive-ui")['NModalProvider']
    'LazyNNotificationProvider': typeof import("naive-ui")['NNotificationProvider']
    'LazyNNumberAnimation': typeof import("naive-ui")['NNumberAnimation']
    'LazyNPageHeader': typeof import("naive-ui")['NPageHeader']
    'LazyNPagination': typeof import("naive-ui")['NPagination']
    'LazyNPopconfirm': typeof import("naive-ui")['NPopconfirm']
    'LazyNPopover': typeof import("naive-ui")['NPopover']
    'LazyNPopselect': typeof import("naive-ui")['NPopselect']
    'LazyNProgress': typeof import("naive-ui")['NProgress']
    'LazyNQrCode': typeof import("naive-ui")['NQrCode']
    'LazyNRadio': typeof import("naive-ui")['NRadio']
    'LazyNRadioButton': typeof import("naive-ui")['NRadioButton']
    'LazyNRadioGroup': typeof import("naive-ui")['NRadioGroup']
    'LazyNRate': typeof import("naive-ui")['NRate']
    'LazyNResult': typeof import("naive-ui")['NResult']
    'LazyNScrollbar': typeof import("naive-ui")['NScrollbar']
    'LazyNSelect': typeof import("naive-ui")['NSelect']
    'LazyNSkeleton': typeof import("naive-ui")['NSkeleton']
    'LazyNSlider': typeof import("naive-ui")['NSlider']
    'LazyNSpace': typeof import("naive-ui")['NSpace']
    'LazyNSpin': typeof import("naive-ui")['NSpin']
    'LazyNSplit': typeof import("naive-ui")['NSplit']
    'LazyNStatistic': typeof import("naive-ui")['NStatistic']
    'LazyNStep': typeof import("naive-ui")['NStep']
    'LazyNSteps': typeof import("naive-ui")['NSteps']
    'LazyNSwitch': typeof import("naive-ui")['NSwitch']
    'LazyNTable': typeof import("naive-ui")['NTable']
    'LazyNTbody': typeof import("naive-ui")['NTbody']
    'LazyNTd': typeof import("naive-ui")['NTd']
    'LazyNTh': typeof import("naive-ui")['NTh']
    'LazyNThead': typeof import("naive-ui")['NThead']
    'LazyNTr': typeof import("naive-ui")['NTr']
    'LazyNTab': typeof import("naive-ui")['NTab']
    'LazyNTabPane': typeof import("naive-ui")['NTabPane']
    'LazyNTabs': typeof import("naive-ui")['NTabs']
    'LazyNTag': typeof import("naive-ui")['NTag']
    'LazyNThing': typeof import("naive-ui")['NThing']
    'LazyNTime': typeof import("naive-ui")['NTime']
    'LazyNTimePicker': typeof import("naive-ui")['NTimePicker']
    'LazyNTimeline': typeof import("naive-ui")['NTimeline']
    'LazyNTimelineItem': typeof import("naive-ui")['NTimelineItem']
    'LazyNTooltip': typeof import("naive-ui")['NTooltip']
    'LazyNTransfer': typeof import("naive-ui")['NTransfer']
    'LazyNTree': typeof import("naive-ui")['NTree']
    'LazyNTreeSelect': typeof import("naive-ui")['NTreeSelect']
    'LazyNA': typeof import("naive-ui")['NA']
    'LazyNBlockquote': typeof import("naive-ui")['NBlockquote']
    'LazyNH1': typeof import("naive-ui")['NH1']
    'LazyNH2': typeof import("naive-ui")['NH2']
    'LazyNH3': typeof import("naive-ui")['NH3']
    'LazyNH4': typeof import("naive-ui")['NH4']
    'LazyNH5': typeof import("naive-ui")['NH5']
    'LazyNH6': typeof import("naive-ui")['NH6']
    'LazyNHr': typeof import("naive-ui")['NHr']
    'LazyNLi': typeof import("naive-ui")['NLi']
    'LazyNOl': typeof import("naive-ui")['NOl']
    'LazyNP': typeof import("naive-ui")['NP']
    'LazyNText': typeof import("naive-ui")['NText']
    'LazyNUl': typeof import("naive-ui")['NUl']
    'LazyNUpload': typeof import("naive-ui")['NUpload']
    'LazyNUploadDragger': typeof import("naive-ui")['NUploadDragger']
    'LazyNUploadFileList': typeof import("naive-ui")['NUploadFileList']
    'LazyNUploadTrigger': typeof import("naive-ui")['NUploadTrigger']
    'LazyNVirtualList': typeof import("naive-ui")['NVirtualList']
    'LazyNWatermark': typeof import("naive-ui")['NWatermark']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNaiveDrawerLink': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNaiveLoadingBar': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNaiveNotification': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNDrawer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['NDrawer']>
    'LazyNDrawerContent': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['NDrawerContent']>
    'LazyNModal': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['NModal']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AccountProfile: typeof import("../components/account/AccountProfile.vue")['default']
export const AppBar: typeof import("../components/app/AppBar.vue")['default']
export const AppBarNotification: typeof import("../components/app/AppBarNotification.vue")['default']
export const AppBarProfile: typeof import("../components/app/AppBarProfile.vue")['default']
export const AppBarSearch: typeof import("../components/app/AppBarSearch.vue")['default']
export const AppSideBar: typeof import("../components/app/AppSideBar.vue")['default']
export const CommonLabel: typeof import("../components/common/CommonLabel.vue")['default']
export const QuoteLineChart: typeof import("../components/quote/LineChart.vue")['default']
export const QuotePieChart: typeof import("../components/quote/PieChart.vue")['default']
export const QuoteRecent: typeof import("../components/quote/QuoteRecent.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NaiveConfig: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveConfig.vue")['default']
export const NaiveNavbar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNavbar.vue")['default']
export const NaiveColorModeSwitch: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveColorModeSwitch.vue")['default']
export const NaiveTabbar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveTabbar.vue")['default']
export const NaiveMenuLink: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveMenuLink.vue")['default']
export const NaiveLayoutSidebar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutSidebar.vue")['default']
export const NaiveLayoutNavbar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutNavbar.vue")['default']
export const NaiveDrawerLink: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveDrawerLink.client.vue")['default']
export const NaiveLoadingBar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLoadingBar.client.vue")['default']
export const NaiveNotification: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNotification.client.vue")['default']
export const NaiveIcon: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveIcon.vue")['default']
export const NThemeEditor: typeof import("naive-ui")['NThemeEditor']
export const NAffix: typeof import("naive-ui")['NAffix']
export const NAlert: typeof import("naive-ui")['NAlert']
export const NAnchor: typeof import("naive-ui")['NAnchor']
export const NAnchorLink: typeof import("naive-ui")['NAnchorLink']
export const NAutoComplete: typeof import("naive-ui")['NAutoComplete']
export const NAvatar: typeof import("naive-ui")['NAvatar']
export const NAvatarGroup: typeof import("naive-ui")['NAvatarGroup']
export const NBackTop: typeof import("naive-ui")['NBackTop']
export const NBadge: typeof import("naive-ui")['NBadge']
export const NBreadcrumb: typeof import("naive-ui")['NBreadcrumb']
export const NBreadcrumbItem: typeof import("naive-ui")['NBreadcrumbItem']
export const NButton: typeof import("naive-ui")['NButton']
export const NButtonGroup: typeof import("naive-ui")['NButtonGroup']
export const NCalendar: typeof import("naive-ui")['NCalendar']
export const NCard: typeof import("naive-ui")['NCard']
export const NCarousel: typeof import("naive-ui")['NCarousel']
export const NCarouselItem: typeof import("naive-ui")['NCarouselItem']
export const NCascader: typeof import("naive-ui")['NCascader']
export const NCheckbox: typeof import("naive-ui")['NCheckbox']
export const NCheckboxGroup: typeof import("naive-ui")['NCheckboxGroup']
export const NCode: typeof import("naive-ui")['NCode']
export const NCollapse: typeof import("naive-ui")['NCollapse']
export const NCollapseItem: typeof import("naive-ui")['NCollapseItem']
export const NCollapseTransition: typeof import("naive-ui")['NCollapseTransition']
export const NColorPicker: typeof import("naive-ui")['NColorPicker']
export const NConfigProvider: typeof import("naive-ui")['NConfigProvider']
export const NCountdown: typeof import("naive-ui")['NCountdown']
export const NDataTable: typeof import("naive-ui")['NDataTable']
export const NDatePicker: typeof import("naive-ui")['NDatePicker']
export const NDescriptions: typeof import("naive-ui")['NDescriptions']
export const NDescriptionsItem: typeof import("naive-ui")['NDescriptionsItem']
export const NDialog: typeof import("naive-ui")['NDialog']
export const NDialogProvider: typeof import("naive-ui")['NDialogProvider']
export const NDivider: typeof import("naive-ui")['NDivider']
export const NDrawer: typeof import("naive-ui")['NDrawer']
export const NDrawerContent: typeof import("naive-ui")['NDrawerContent']
export const NDropdown: typeof import("naive-ui")['NDropdown']
export const NDynamicInput: typeof import("naive-ui")['NDynamicInput']
export const NDynamicTags: typeof import("naive-ui")['NDynamicTags']
export const NElement: typeof import("naive-ui")['NElement']
export const NEl: typeof import("naive-ui")['NEl']
export const NEllipsis: typeof import("naive-ui")['NEllipsis']
export const NPerformantEllipsis: typeof import("naive-ui")['NPerformantEllipsis']
export const NEmpty: typeof import("naive-ui")['NEmpty']
export const NEquation: typeof import("naive-ui")['NEquation']
export const NFlex: typeof import("naive-ui")['NFlex']
export const NFloatButton: typeof import("naive-ui")['NFloatButton']
export const NFloatButtonGroup: typeof import("naive-ui")['NFloatButtonGroup']
export const NForm: typeof import("naive-ui")['NForm']
export const NFormItem: typeof import("naive-ui")['NFormItem']
export const NFormItemCol: typeof import("naive-ui")['NFormItemCol']
export const NFormItemGridItem: typeof import("naive-ui")['NFormItemGridItem']
export const NFormItemGi: typeof import("naive-ui")['NFormItemGi']
export const NFormItemRow: typeof import("naive-ui")['NFormItemRow']
export const NGlobalStyle: typeof import("naive-ui")['NGlobalStyle']
export const NGradientText: typeof import("naive-ui")['NGradientText']
export const NGrid: typeof import("naive-ui")['NGrid']
export const NGridItem: typeof import("naive-ui")['NGridItem']
export const NGi: typeof import("naive-ui")['NGi']
export const NHighlight: typeof import("naive-ui")['NHighlight']
export const NIcon: typeof import("naive-ui")['NIcon']
export const NIconWrapper: typeof import("naive-ui")['NIconWrapper']
export const NImage: typeof import("naive-ui")['NImage']
export const NImageGroup: typeof import("naive-ui")['NImageGroup']
export const NInfiniteScroll: typeof import("naive-ui")['NInfiniteScroll']
export const NInput: typeof import("naive-ui")['NInput']
export const NInputGroup: typeof import("naive-ui")['NInputGroup']
export const NInputGroupLabel: typeof import("naive-ui")['NInputGroupLabel']
export const NInputNumber: typeof import("naive-ui")['NInputNumber']
export const NLayout: typeof import("naive-ui")['NLayout']
export const NLayoutContent: typeof import("naive-ui")['NLayoutContent']
export const NLayoutFooter: typeof import("naive-ui")['NLayoutFooter']
export const NLayoutHeader: typeof import("naive-ui")['NLayoutHeader']
export const NLayoutSider: typeof import("naive-ui")['NLayoutSider']
export const NCol: typeof import("naive-ui")['NCol']
export const NRow: typeof import("naive-ui")['NRow']
export const NLegacyTransfer: typeof import("naive-ui")['NLegacyTransfer']
export const NList: typeof import("naive-ui")['NList']
export const NListItem: typeof import("naive-ui")['NListItem']
export const NLoadingBarProvider: typeof import("naive-ui")['NLoadingBarProvider']
export const NLog: typeof import("naive-ui")['NLog']
export const NMarqueue: typeof import("naive-ui")['NMarqueue']
export const NMention: typeof import("naive-ui")['NMention']
export const NMenu: typeof import("naive-ui")['NMenu']
export const NMessageProvider: typeof import("naive-ui")['NMessageProvider']
export const NModal: typeof import("naive-ui")['NModal']
export const NModalProvider: typeof import("naive-ui")['NModalProvider']
export const NNotificationProvider: typeof import("naive-ui")['NNotificationProvider']
export const NNumberAnimation: typeof import("naive-ui")['NNumberAnimation']
export const NPageHeader: typeof import("naive-ui")['NPageHeader']
export const NPagination: typeof import("naive-ui")['NPagination']
export const NPopconfirm: typeof import("naive-ui")['NPopconfirm']
export const NPopover: typeof import("naive-ui")['NPopover']
export const NPopselect: typeof import("naive-ui")['NPopselect']
export const NProgress: typeof import("naive-ui")['NProgress']
export const NQrCode: typeof import("naive-ui")['NQrCode']
export const NRadio: typeof import("naive-ui")['NRadio']
export const NRadioButton: typeof import("naive-ui")['NRadioButton']
export const NRadioGroup: typeof import("naive-ui")['NRadioGroup']
export const NRate: typeof import("naive-ui")['NRate']
export const NResult: typeof import("naive-ui")['NResult']
export const NScrollbar: typeof import("naive-ui")['NScrollbar']
export const NSelect: typeof import("naive-ui")['NSelect']
export const NSkeleton: typeof import("naive-ui")['NSkeleton']
export const NSlider: typeof import("naive-ui")['NSlider']
export const NSpace: typeof import("naive-ui")['NSpace']
export const NSpin: typeof import("naive-ui")['NSpin']
export const NSplit: typeof import("naive-ui")['NSplit']
export const NStatistic: typeof import("naive-ui")['NStatistic']
export const NStep: typeof import("naive-ui")['NStep']
export const NSteps: typeof import("naive-ui")['NSteps']
export const NSwitch: typeof import("naive-ui")['NSwitch']
export const NTable: typeof import("naive-ui")['NTable']
export const NTbody: typeof import("naive-ui")['NTbody']
export const NTd: typeof import("naive-ui")['NTd']
export const NTh: typeof import("naive-ui")['NTh']
export const NThead: typeof import("naive-ui")['NThead']
export const NTr: typeof import("naive-ui")['NTr']
export const NTab: typeof import("naive-ui")['NTab']
export const NTabPane: typeof import("naive-ui")['NTabPane']
export const NTabs: typeof import("naive-ui")['NTabs']
export const NTag: typeof import("naive-ui")['NTag']
export const NThing: typeof import("naive-ui")['NThing']
export const NTime: typeof import("naive-ui")['NTime']
export const NTimePicker: typeof import("naive-ui")['NTimePicker']
export const NTimeline: typeof import("naive-ui")['NTimeline']
export const NTimelineItem: typeof import("naive-ui")['NTimelineItem']
export const NTooltip: typeof import("naive-ui")['NTooltip']
export const NTransfer: typeof import("naive-ui")['NTransfer']
export const NTree: typeof import("naive-ui")['NTree']
export const NTreeSelect: typeof import("naive-ui")['NTreeSelect']
export const NA: typeof import("naive-ui")['NA']
export const NBlockquote: typeof import("naive-ui")['NBlockquote']
export const NH1: typeof import("naive-ui")['NH1']
export const NH2: typeof import("naive-ui")['NH2']
export const NH3: typeof import("naive-ui")['NH3']
export const NH4: typeof import("naive-ui")['NH4']
export const NH5: typeof import("naive-ui")['NH5']
export const NH6: typeof import("naive-ui")['NH6']
export const NHr: typeof import("naive-ui")['NHr']
export const NLi: typeof import("naive-ui")['NLi']
export const NOl: typeof import("naive-ui")['NOl']
export const NP: typeof import("naive-ui")['NP']
export const NText: typeof import("naive-ui")['NText']
export const NUl: typeof import("naive-ui")['NUl']
export const NUpload: typeof import("naive-ui")['NUpload']
export const NUploadDragger: typeof import("naive-ui")['NUploadDragger']
export const NUploadFileList: typeof import("naive-ui")['NUploadFileList']
export const NUploadTrigger: typeof import("naive-ui")['NUploadTrigger']
export const NVirtualList: typeof import("naive-ui")['NVirtualList']
export const NWatermark: typeof import("naive-ui")['NWatermark']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const NaiveDrawerLink: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const NaiveLoadingBar: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const NaiveNotification: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const NDrawer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['NDrawer']>
export const NDrawerContent: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['NDrawerContent']>
export const NModal: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['NModal']>
export const LazyAccountProfile: typeof import("../components/account/AccountProfile.vue")['default']
export const LazyAppBar: typeof import("../components/app/AppBar.vue")['default']
export const LazyAppBarNotification: typeof import("../components/app/AppBarNotification.vue")['default']
export const LazyAppBarProfile: typeof import("../components/app/AppBarProfile.vue")['default']
export const LazyAppBarSearch: typeof import("../components/app/AppBarSearch.vue")['default']
export const LazyAppSideBar: typeof import("../components/app/AppSideBar.vue")['default']
export const LazyCommonLabel: typeof import("../components/common/CommonLabel.vue")['default']
export const LazyQuoteLineChart: typeof import("../components/quote/LineChart.vue")['default']
export const LazyQuotePieChart: typeof import("../components/quote/PieChart.vue")['default']
export const LazyQuoteRecent: typeof import("../components/quote/QuoteRecent.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNaiveConfig: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveConfig.vue")['default']
export const LazyNaiveNavbar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNavbar.vue")['default']
export const LazyNaiveColorModeSwitch: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveColorModeSwitch.vue")['default']
export const LazyNaiveTabbar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveTabbar.vue")['default']
export const LazyNaiveMenuLink: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveMenuLink.vue")['default']
export const LazyNaiveLayoutSidebar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutSidebar.vue")['default']
export const LazyNaiveLayoutNavbar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLayoutNavbar.vue")['default']
export const LazyNaiveDrawerLink: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveDrawerLink.client.vue")['default']
export const LazyNaiveLoadingBar: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveLoadingBar.client.vue")['default']
export const LazyNaiveNotification: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveNotification.client.vue")['default']
export const LazyNaiveIcon: typeof import("../node_modules/@bg-dev/nuxt-naiveui/dist/runtime/components/NaiveIcon.vue")['default']
export const LazyNThemeEditor: typeof import("naive-ui")['NThemeEditor']
export const LazyNAffix: typeof import("naive-ui")['NAffix']
export const LazyNAlert: typeof import("naive-ui")['NAlert']
export const LazyNAnchor: typeof import("naive-ui")['NAnchor']
export const LazyNAnchorLink: typeof import("naive-ui")['NAnchorLink']
export const LazyNAutoComplete: typeof import("naive-ui")['NAutoComplete']
export const LazyNAvatar: typeof import("naive-ui")['NAvatar']
export const LazyNAvatarGroup: typeof import("naive-ui")['NAvatarGroup']
export const LazyNBackTop: typeof import("naive-ui")['NBackTop']
export const LazyNBadge: typeof import("naive-ui")['NBadge']
export const LazyNBreadcrumb: typeof import("naive-ui")['NBreadcrumb']
export const LazyNBreadcrumbItem: typeof import("naive-ui")['NBreadcrumbItem']
export const LazyNButton: typeof import("naive-ui")['NButton']
export const LazyNButtonGroup: typeof import("naive-ui")['NButtonGroup']
export const LazyNCalendar: typeof import("naive-ui")['NCalendar']
export const LazyNCard: typeof import("naive-ui")['NCard']
export const LazyNCarousel: typeof import("naive-ui")['NCarousel']
export const LazyNCarouselItem: typeof import("naive-ui")['NCarouselItem']
export const LazyNCascader: typeof import("naive-ui")['NCascader']
export const LazyNCheckbox: typeof import("naive-ui")['NCheckbox']
export const LazyNCheckboxGroup: typeof import("naive-ui")['NCheckboxGroup']
export const LazyNCode: typeof import("naive-ui")['NCode']
export const LazyNCollapse: typeof import("naive-ui")['NCollapse']
export const LazyNCollapseItem: typeof import("naive-ui")['NCollapseItem']
export const LazyNCollapseTransition: typeof import("naive-ui")['NCollapseTransition']
export const LazyNColorPicker: typeof import("naive-ui")['NColorPicker']
export const LazyNConfigProvider: typeof import("naive-ui")['NConfigProvider']
export const LazyNCountdown: typeof import("naive-ui")['NCountdown']
export const LazyNDataTable: typeof import("naive-ui")['NDataTable']
export const LazyNDatePicker: typeof import("naive-ui")['NDatePicker']
export const LazyNDescriptions: typeof import("naive-ui")['NDescriptions']
export const LazyNDescriptionsItem: typeof import("naive-ui")['NDescriptionsItem']
export const LazyNDialog: typeof import("naive-ui")['NDialog']
export const LazyNDialogProvider: typeof import("naive-ui")['NDialogProvider']
export const LazyNDivider: typeof import("naive-ui")['NDivider']
export const LazyNDrawer: typeof import("naive-ui")['NDrawer']
export const LazyNDrawerContent: typeof import("naive-ui")['NDrawerContent']
export const LazyNDropdown: typeof import("naive-ui")['NDropdown']
export const LazyNDynamicInput: typeof import("naive-ui")['NDynamicInput']
export const LazyNDynamicTags: typeof import("naive-ui")['NDynamicTags']
export const LazyNElement: typeof import("naive-ui")['NElement']
export const LazyNEl: typeof import("naive-ui")['NEl']
export const LazyNEllipsis: typeof import("naive-ui")['NEllipsis']
export const LazyNPerformantEllipsis: typeof import("naive-ui")['NPerformantEllipsis']
export const LazyNEmpty: typeof import("naive-ui")['NEmpty']
export const LazyNEquation: typeof import("naive-ui")['NEquation']
export const LazyNFlex: typeof import("naive-ui")['NFlex']
export const LazyNFloatButton: typeof import("naive-ui")['NFloatButton']
export const LazyNFloatButtonGroup: typeof import("naive-ui")['NFloatButtonGroup']
export const LazyNForm: typeof import("naive-ui")['NForm']
export const LazyNFormItem: typeof import("naive-ui")['NFormItem']
export const LazyNFormItemCol: typeof import("naive-ui")['NFormItemCol']
export const LazyNFormItemGridItem: typeof import("naive-ui")['NFormItemGridItem']
export const LazyNFormItemGi: typeof import("naive-ui")['NFormItemGi']
export const LazyNFormItemRow: typeof import("naive-ui")['NFormItemRow']
export const LazyNGlobalStyle: typeof import("naive-ui")['NGlobalStyle']
export const LazyNGradientText: typeof import("naive-ui")['NGradientText']
export const LazyNGrid: typeof import("naive-ui")['NGrid']
export const LazyNGridItem: typeof import("naive-ui")['NGridItem']
export const LazyNGi: typeof import("naive-ui")['NGi']
export const LazyNHighlight: typeof import("naive-ui")['NHighlight']
export const LazyNIcon: typeof import("naive-ui")['NIcon']
export const LazyNIconWrapper: typeof import("naive-ui")['NIconWrapper']
export const LazyNImage: typeof import("naive-ui")['NImage']
export const LazyNImageGroup: typeof import("naive-ui")['NImageGroup']
export const LazyNInfiniteScroll: typeof import("naive-ui")['NInfiniteScroll']
export const LazyNInput: typeof import("naive-ui")['NInput']
export const LazyNInputGroup: typeof import("naive-ui")['NInputGroup']
export const LazyNInputGroupLabel: typeof import("naive-ui")['NInputGroupLabel']
export const LazyNInputNumber: typeof import("naive-ui")['NInputNumber']
export const LazyNLayout: typeof import("naive-ui")['NLayout']
export const LazyNLayoutContent: typeof import("naive-ui")['NLayoutContent']
export const LazyNLayoutFooter: typeof import("naive-ui")['NLayoutFooter']
export const LazyNLayoutHeader: typeof import("naive-ui")['NLayoutHeader']
export const LazyNLayoutSider: typeof import("naive-ui")['NLayoutSider']
export const LazyNCol: typeof import("naive-ui")['NCol']
export const LazyNRow: typeof import("naive-ui")['NRow']
export const LazyNLegacyTransfer: typeof import("naive-ui")['NLegacyTransfer']
export const LazyNList: typeof import("naive-ui")['NList']
export const LazyNListItem: typeof import("naive-ui")['NListItem']
export const LazyNLoadingBarProvider: typeof import("naive-ui")['NLoadingBarProvider']
export const LazyNLog: typeof import("naive-ui")['NLog']
export const LazyNMarqueue: typeof import("naive-ui")['NMarqueue']
export const LazyNMention: typeof import("naive-ui")['NMention']
export const LazyNMenu: typeof import("naive-ui")['NMenu']
export const LazyNMessageProvider: typeof import("naive-ui")['NMessageProvider']
export const LazyNModal: typeof import("naive-ui")['NModal']
export const LazyNModalProvider: typeof import("naive-ui")['NModalProvider']
export const LazyNNotificationProvider: typeof import("naive-ui")['NNotificationProvider']
export const LazyNNumberAnimation: typeof import("naive-ui")['NNumberAnimation']
export const LazyNPageHeader: typeof import("naive-ui")['NPageHeader']
export const LazyNPagination: typeof import("naive-ui")['NPagination']
export const LazyNPopconfirm: typeof import("naive-ui")['NPopconfirm']
export const LazyNPopover: typeof import("naive-ui")['NPopover']
export const LazyNPopselect: typeof import("naive-ui")['NPopselect']
export const LazyNProgress: typeof import("naive-ui")['NProgress']
export const LazyNQrCode: typeof import("naive-ui")['NQrCode']
export const LazyNRadio: typeof import("naive-ui")['NRadio']
export const LazyNRadioButton: typeof import("naive-ui")['NRadioButton']
export const LazyNRadioGroup: typeof import("naive-ui")['NRadioGroup']
export const LazyNRate: typeof import("naive-ui")['NRate']
export const LazyNResult: typeof import("naive-ui")['NResult']
export const LazyNScrollbar: typeof import("naive-ui")['NScrollbar']
export const LazyNSelect: typeof import("naive-ui")['NSelect']
export const LazyNSkeleton: typeof import("naive-ui")['NSkeleton']
export const LazyNSlider: typeof import("naive-ui")['NSlider']
export const LazyNSpace: typeof import("naive-ui")['NSpace']
export const LazyNSpin: typeof import("naive-ui")['NSpin']
export const LazyNSplit: typeof import("naive-ui")['NSplit']
export const LazyNStatistic: typeof import("naive-ui")['NStatistic']
export const LazyNStep: typeof import("naive-ui")['NStep']
export const LazyNSteps: typeof import("naive-ui")['NSteps']
export const LazyNSwitch: typeof import("naive-ui")['NSwitch']
export const LazyNTable: typeof import("naive-ui")['NTable']
export const LazyNTbody: typeof import("naive-ui")['NTbody']
export const LazyNTd: typeof import("naive-ui")['NTd']
export const LazyNTh: typeof import("naive-ui")['NTh']
export const LazyNThead: typeof import("naive-ui")['NThead']
export const LazyNTr: typeof import("naive-ui")['NTr']
export const LazyNTab: typeof import("naive-ui")['NTab']
export const LazyNTabPane: typeof import("naive-ui")['NTabPane']
export const LazyNTabs: typeof import("naive-ui")['NTabs']
export const LazyNTag: typeof import("naive-ui")['NTag']
export const LazyNThing: typeof import("naive-ui")['NThing']
export const LazyNTime: typeof import("naive-ui")['NTime']
export const LazyNTimePicker: typeof import("naive-ui")['NTimePicker']
export const LazyNTimeline: typeof import("naive-ui")['NTimeline']
export const LazyNTimelineItem: typeof import("naive-ui")['NTimelineItem']
export const LazyNTooltip: typeof import("naive-ui")['NTooltip']
export const LazyNTransfer: typeof import("naive-ui")['NTransfer']
export const LazyNTree: typeof import("naive-ui")['NTree']
export const LazyNTreeSelect: typeof import("naive-ui")['NTreeSelect']
export const LazyNA: typeof import("naive-ui")['NA']
export const LazyNBlockquote: typeof import("naive-ui")['NBlockquote']
export const LazyNH1: typeof import("naive-ui")['NH1']
export const LazyNH2: typeof import("naive-ui")['NH2']
export const LazyNH3: typeof import("naive-ui")['NH3']
export const LazyNH4: typeof import("naive-ui")['NH4']
export const LazyNH5: typeof import("naive-ui")['NH5']
export const LazyNH6: typeof import("naive-ui")['NH6']
export const LazyNHr: typeof import("naive-ui")['NHr']
export const LazyNLi: typeof import("naive-ui")['NLi']
export const LazyNOl: typeof import("naive-ui")['NOl']
export const LazyNP: typeof import("naive-ui")['NP']
export const LazyNText: typeof import("naive-ui")['NText']
export const LazyNUl: typeof import("naive-ui")['NUl']
export const LazyNUpload: typeof import("naive-ui")['NUpload']
export const LazyNUploadDragger: typeof import("naive-ui")['NUploadDragger']
export const LazyNUploadFileList: typeof import("naive-ui")['NUploadFileList']
export const LazyNUploadTrigger: typeof import("naive-ui")['NUploadTrigger']
export const LazyNVirtualList: typeof import("naive-ui")['NVirtualList']
export const LazyNWatermark: typeof import("naive-ui")['NWatermark']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNaiveDrawerLink: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNaiveLoadingBar: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNaiveNotification: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNDrawer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['NDrawer']>
export const LazyNDrawerContent: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['NDrawerContent']>
export const LazyNModal: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['NModal']>

export const componentNames: string[]
